Models/MeetingInfo.cs
namespace MeetingApp.Models;

public class MeetingInfo{
    public int Id { get; set; }
    public string? Location { get; set; }
    public DateTime? Date { get; set; }
    public int NumberOfPeople { get; set; }

    public MeetingInfo(int id, string? location, DateTime? date, int numberOfPeople)
    {
        Id = id;
        Location = location;
        Date = date;
        NumberOfPeople = numberOfPeople;
    }

}

Models/Repository.cs
namespace MeetingApp.Models;

public static class Repository
{
    private static List<UserInfo> userInfo = new List<UserInfo>(){};
        
    static Repository(){
        userInfo.Add(new UserInfo(){Id = 1,Name = "Kenan", Phone = "555-555-5555", Email = "VgQ5r@example.com",WillAttend = true});
        userInfo.Add(new UserInfo(){Id = 2,Name = "John", Phone = "555-555-5555", Email = "example@example.com",WillAttend = false});
        userInfo.Add(new UserInfo(){Id = 3,Name = "Jane", Phone = "555-555-5555", Email = "example@example.com",WillAttend = true});
    }
    public static List<UserInfo> GetUserInfo() => userInfo;
    public static void AddUserInfo(UserInfo userinfo){
         userinfo.Id = userInfo.Count() + 1;
         userInfo.Add(userinfo);
    }

    public static UserInfo? GetById(int id) => userInfo.FirstOrDefault(i=> i.Id == id);
}

Models/UserInfo.cs
using System.ComponentModel.DataAnnotations;


namespace MeetingApp.Models;

public class UserInfo
{
    public int? Id { get; set; }
    
    [Required]
    public string? Name { get; set; }
    
    [Required]
    public string? Phone { get; set; }

    [Required]
    [EmailAddress]
    public string? Email { get; set; }

    [Required]
    public bool WillAttend { get; set; }

    
}

Controllers/HomeController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers;
public class HomeController : Controller
{
    public IActionResult Index()
    {
        int viewCount = Repository.GetUserInfo().Where(x => x.WillAttend == true).Count();
        var meetingInfo = new MeetingInfo(1, "Location 1",new DateTime(2022, 12, 10),viewCount);
        return View(meetingInfo);
    }
}

Controllers/MeetingController.cs
using Microsoft.AspNetCore.Mvc;
using MeetingApp.Models;

namespace MeetingApp.Controllers;

public class MeetingController : Controller
{
    public IActionResult Apply()
    {
        return View();
    }
    [HttpPost]
    public IActionResult Apply(UserInfo userInfo)
    {   
        if(ModelState.IsValid){
            Repository.AddUserInfo(userInfo);
            ViewBag.UserCount = Repository.GetUserInfo().Where(x => x.WillAttend == true).Count();
            return View("Thanks",userInfo);
        }
        else{
            return View(userInfo);
        }
    }
    public IActionResult List()
    {
        return View(Repository.GetUserInfo());
    }

    public IActionResult Details(int id)
    {
        return View(Repository.GetById(id));
    }
}

Views/Home/index.cshtml
@model MeetingInfo
@{
    ViewBag.Title = "MainPage";
    Layout = "_Layout2";
}
<main class="text-center">

    <h1 class = "h4">Welcome Meeting</h1>
    <p>Notify your Participation Status</p>
    
    <div class="card my-2">
        <ul class="list-group list-group flush">
            <li class="list-group-item">@Model.Location</li>
            <li class="list-group-item">@Model.Date will take place on</li>
            <li class="list-group-item">@Model.NumberOfPeople Participate</li>
        </ul>
    </div>
    <a class= "btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply">Login</a>
</main>

Views/Meeting/Apply.cshtml
@model UserInfo
@{
    ViewBag.Title = "Apply";
}
<h1 class="h4 text-center">MeetingApp Entry Form</h1>
<form method="post" asp-controller="Meeting" asp-action="Apply">
    <div asp-validation-summary="All" style="color: red;"></div>
    <div class="mb-3">
        <label asp-for="Name" class="form-label">Name</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Phone</label>
        <input asp-for="Phone" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="WillAttend" class="form-label">Participation status</label>
        <select asp-for="WillAttend" class="form-select">
            <option value="true">Yes,I'm coming</option>
            <option value="false">No,I'm not coming</option>
        </select>
    </div>
    <button class="btn btn-primary" type="submit">Save</button>
</form>

Views/Meeting/Details.cshtml
@model UserInfo
@{
    ViewBag.Title = "MeetingDetails";
}

@{ 
    var className = Model.WillAttend == true ? "success" : "danger";
    var isCheck = Model.WillAttend == true ? "participating" : "Does Not Participating";  
}


<main class="text-center">
    <h1 class="h4">Application Details</h1>
    <p>
        <span class = "badge text-bg-@className">@isCheck</span>
    </p>
    <p>Name: @Model.Name</p>
    <p>Phone: @Model.Phone</p>
    <p>Email: @Model.Email</p>

</main>

Views/Meeting/List.cshtml
@model List<UserInfo>
@{
    ViewBag.Title = "MeetingList";
}
<main class="text-center">

    <h1 class="h4">Meeting listesi</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Name</td>
                <td>Katilim durumu</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model){
                var isCheck = item.WillAttend == true ? "Yes" : "No";
                var className = item.WillAttend == true ? "table-success" : "table-danger";
                var btn_className = item.WillAttend == true ? "btn btn-success" : "btn btn-danger";
                <tr class="@className">
                    <td>@item.Name</td>
                    <td>@isCheck</td>
                    <td>
                        <a class="@btn_className" asp-controller="Meeting" asp-action="Details" asp-route-id="@item.Id">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</main>

Views/Meeting/Thanks.cshtml
@model UserInfo
@{
    ViewBag.Title = "Meeting";
}
<main class="text-center">
    <h1 class="h4">Meeting</h1>

    @if(Model.WillAttend){
        <p>Thank you,There are @ViewBag.UserCount people attending the meeting with you.</p>
        <a class= "btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="List">list of participants</a>
    }else{
        <p>@Model.Name , We are sorry that you did not participate</p>
        <a class= "btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply">Apply for</a>
    }
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css"/>
    <title>@ViewBag.Title - MeetingApp</title>
</head>

<body>

    <div class="bg-primary text-white p-2 text-center">
         <a asp-controller="Home" asp-action="Index" style="text-decoration: none;" class="text-white" >MeetingApp</a>
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>

        </div>
    </div>
</body>

</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css"/>

    <title>@ViewBag.Title - MeetingApp</title>
</head>

<body>

    <div class="bg-primary text-white p-2 text-center">
        MeetingApp
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto ">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>

        </div>
    </div>
</body>

</html>